from __future__ import annotations

import argparse
import os
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F

try:
    from vllm import LLM, SamplingParams
except ImportError as exc:
    raise SystemExit(
        "vLLM is required for this script. Install a vLLM wheel that matches "
        "your CUDA and PyTorch build, then re-run this script."
    ) from exc


os.environ.setdefault("VLLM_ALLOW_INSECURE_SERIALIZATION", "1")

REFERENCE_PATH = Path("all_layers_hidden_states.npz")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Compare Gemma 4 prompt activations extracted through vLLM against "
            "the Hugging Face reference tensors saved in an NPZ."
        )
    )
    parser.add_argument(
        "--reference",
        type=Path,
        default=REFERENCE_PATH,
        help="Path to the reference NPZ generated by extract_all_hidden_states_npz.py.",
    )
    parser.add_argument(
        "--min-cosine",
        type=float,
        default=0.998,
        help="Minimum acceptable cosine similarity for every layer.",
    )
    return parser.parse_args()


def load_scalar_string(array: np.ndarray) -> str:
    value = array.item() if hasattr(array, "item") else array
    return str(value)


def cosine_similarity(left: torch.Tensor, right: torch.Tensor) -> float:
    left = left.reshape(1, -1).to(dtype=torch.float32)
    right = right.reshape(1, -1).to(dtype=torch.float32)
    return float(F.cosine_similarity(left, right).item())


def main() -> None:
    args = parse_args()
    reference = np.load(args.reference)
    reference_hidden_states = reference["hidden_states"]
    layer_indices = reference["layer_indices"].tolist()
    model_id = load_scalar_string(reference["model_id"])
    prompt = load_scalar_string(reference["prompt"])

    llm = LLM(
        model=model_id,
        trust_remote_code=True,
        dtype="bfloat16",
        tensor_parallel_size=1,
        enforce_eager=True,
        compilation_config={"mode": 0},
        extract_activation_layers=layer_indices,
    )
    outputs = llm.generate(
        [prompt],
        SamplingParams(max_tokens=1, temperature=0.0),
        use_tqdm=False,
    )

    completion = outputs[0].outputs[0]
    if not completion.activations:
        raise RuntimeError("vLLM did not return any prompt activations.")

    min_similarity = 1.0
    print(f"Reference shape: {reference_hidden_states.shape}")
    for layer_idx in layer_indices:
        if layer_idx not in completion.activations:
            raise RuntimeError(f"Missing vLLM activation for layer {layer_idx}.")

        vllm_hidden_state = completion.activations[layer_idx].to(
            device="cpu", dtype=torch.float32
        )
        reference_hidden_state = torch.from_numpy(
            reference_hidden_states[layer_idx]
        ).to(dtype=torch.float32)
        if vllm_hidden_state.ndim == reference_hidden_state.ndim - 1:
            vllm_hidden_state = vllm_hidden_state.unsqueeze(0)

        if tuple(vllm_hidden_state.shape) != tuple(reference_hidden_state.shape):
            raise RuntimeError(
                "Shape mismatch for layer "
                f"{layer_idx}: vLLM={tuple(vllm_hidden_state.shape)} "
                f"reference={tuple(reference_hidden_state.shape)}"
            )

        similarity = cosine_similarity(vllm_hidden_state, reference_hidden_state)
        min_similarity = min(min_similarity, similarity)
        print(
            f"Layer {layer_idx:02d}: cosine={similarity:.8f} "
            f"shape={tuple(vllm_hidden_state.shape)}"
        )

    print(f"Minimum cosine similarity: {min_similarity:.8f}")
    if min_similarity < args.min_cosine:
        raise SystemExit(
            f"Verification failed: minimum cosine {min_similarity:.8f} is below "
            f"{args.min_cosine:.8f}."
        )


if __name__ == "__main__":
    main()
